<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Traits\TraitSeeder;
use App\Models\Bank as Model;

class BanksTableSeeder extends Seeder
{
    use TraitSeeder;

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->smartySeeder(new Model, [
            ['id' => 1, 'code' => '246', 'name' => 'Banco ABC Brasil S.A.'],
            ['id' => 2, 'code' => '748', 'name' => 'Banco Cooperativo Sicredi S.A.'],
            ['id' => 3, 'code' => '117', 'name' => 'Advanced Cc Ltda'],
            ['id' => 4, 'code' => '121', 'name' => 'Banco Agibank S.A.'],
            ['id' => 5, 'code' => '172', 'name' => 'Albatross Ccv S.A'],
            ['id' => 6, 'code' => '188', 'name' => 'Ativa Investimentos S.A'],
            ['id' => 7, 'code' => '280', 'name' => 'Avista S.A. Crédito, Financiamento e Investimento'],
            ['id' => 8, 'code' => '080', 'name' => 'B&T Cc Ltda'],
            ['id' => 9, 'code' => '654', 'name' => 'Banco A.J.Renner'],
            ['id' => 10, 'code' => '246', 'name' => 'Banco ABC Brasil S.A.'],
            ['id' => 11, 'code' => '075', 'name' => 'Banco ABN AMRO S.A'],
            ['id' => 12, 'code' => '121', 'name' => 'Banco Agibank S.A.'],
            ['id' => 13, 'code' => '025', 'name' => 'Banco Alfa S.A.'],
            ['id' => 14, 'code' => '641', 'name' => 'Banco Alvorada S.A.'],
            ['id' => 15, 'code' => '065', 'name' => 'Banco Andbank (Brasil) S.A.'],
            ['id' => 16, 'code' => '213', 'name' => 'Banco Arbi S.A.'],
            ['id' => 17, 'code' => '096', 'name' => 'Banco B3 S.A.'],
            ['id' => 18, 'code' => '024', 'name' => 'Banco BANDEPE S.A.'],
            ['id' => 19, 'code' => '318', 'name' => 'Banco BMG S.A.'],
            ['id' => 20, 'code' => '752', 'name' => 'Banco BNP Paribas Brasil S.A.'],
            ['id' => 21, 'code' => '107', 'name' => 'Banco BOCOM BBM S.A.'],
            ['id' => 22, 'code' => '063', 'name' => 'Banco Bradescard S.A.'],
            ['id' => 23, 'code' => '036', 'name' => 'Banco Bradesco BBI S.A.'],
            ['id' => 24, 'code' => '122', 'name' => 'Banco Bradesco BERJ S.A.'],
            ['id' => 25, 'code' => '204', 'name' => 'Banco Bradesco Cartões S.A.'],
            ['id' => 26, 'code' => '394', 'name' => 'Banco Bradesco Financiamentos S.A.'],
            ['id' => 27, 'code' => '237', 'name' => 'Banco Bradesco S.A.'],
            ['id' => 28, 'code' => '218', 'name' => 'Banco BS2 S.A.'],
            ['id' => 29, 'code' => '208', 'name' => 'Banco BTG Pactual S.A.'],
            ['id' => 30, 'code' => '336', 'name' => 'Banco C6 S.A – C6 Bank'],
            ['id' => 31, 'code' => '473', 'name' => 'Banco Caixa Geral – Brasil S.A.'],
            ['id' => 32, 'code' => '412', 'name' => 'Banco Capital S.A.'],
            ['id' => 33, 'code' => '040', 'name' => 'Banco Cargill S.A.'],
            ['id' => 34, 'code' => '368', 'name' => 'Banco Carrefour'],
            ['id' => 35, 'code' => '266', 'name' => 'Banco Cédula S.A.'],
            ['id' => 36, 'code' => '739', 'name' => 'Banco Cetelem S.A.'],
            ['id' => 37, 'code' => '233', 'name' => 'Banco Cifra S.A.'],
            ['id' => 38, 'code' => '745', 'name' => 'Banco Citibank S.A.'],
            ['id' => 39, 'code' => '241', 'name' => 'Banco Clássico S.A.'],
            ['id' => 40, 'code' => '756', 'name' => 'Banco Cooperativo do Brasil S.A. – BANCOOB'],
            ['id' => 41, 'code' => '748', 'name' => 'Banco Cooperativo Sicredi S.A.'],
            ['id' => 42, 'code' => '222', 'name' => 'Banco Credit Agricole Brasil S.A.'],
            ['id' => 43, 'code' => '505', 'name' => 'Banco Credit Suisse (Brasil) S.A.'],
            ['id' => 44, 'code' => '069', 'name' => 'Banco Crefisa S.A.'],
            ['id' => 45, 'code' => '003', 'name' => 'Banco da Amazônia S.A.'],
            ['id' => 46, 'code' => '083', 'name' => 'Banco da China Brasil S.A.'],
            ['id' => 47, 'code' => '707', 'name' => 'Banco Daycoval S.A.'],
            ['id' => 48, 'code' => '051', 'name' => 'Banco de Desenvolvimento do Espírito Santo S.A.'],
            ['id' => 49, 'code' => '300', 'name' => 'Banco de La Nacion Argentina'],
            ['id' => 50, 'code' => '495', 'name' => 'Banco de La Provincia de Buenos Aires'],
            ['id' => 51, 'code' => '494', 'name' => 'Banco de La Republica Oriental del Uruguay'],
            ['id' => 52, 'code' => '335', 'name' => 'Banco Digio S.A'],
            ['id' => 53, 'code' => '001', 'name' => 'Banco do Brasil S.A.'],
            ['id' => 54, 'code' => '047', 'name' => 'Banco do Estado de Sergipe S.A.'],
            ['id' => 55, 'code' => '037', 'name' => 'Banco do Estado do Pará S.A.'],
            ['id' => 56, 'code' => '041', 'name' => 'Banco do Estado do Rio Grande do Sul S.A.'],
            ['id' => 57, 'code' => '004', 'name' => 'Banco do Nordeste do Brasil S.A.'],
            ['id' => 58, 'code' => '196', 'name' => 'Banco Fair Corretora de Câmbio S.A'],
            ['id' => 59, 'code' => '265', 'name' => 'Banco Fator S.A.'],
            ['id' => 60, 'code' => '224', 'name' => 'Banco Fibra S.A.'],
            ['id' => 61, 'code' => '626', 'name' => 'Banco Ficsa S.A.'],
            ['id' => 62, 'code' => '094', 'name' => 'Banco Finaxis S.A.'],
            ['id' => 63, 'code' => '612', 'name' => 'Banco Guanabara S.A.'],
            ['id' => 64, 'code' => '012', 'name' => 'Banco Inbursa S.A.'],
            ['id' => 65, 'code' => '604', 'name' => 'Banco Industrial do Brasil S.A.'],
            ['id' => 66, 'code' => '653', 'name' => 'Banco Indusval S.A.'],
            ['id' => 67, 'code' => '077', 'name' => 'Banco Inter S.A.'],
            ['id' => 68, 'code' => '249', 'name' => 'Banco Investcred Unibanco S.A.'],
            ['id' => 69, 'code' => '184', 'name' => 'Banco Itaú BBA S.A.'],
            ['id' => 70, 'code' => '029', 'name' => 'Banco Itaú Consignado S.A.'],
            ['id' => 71, 'code' => '479', 'name' => 'Banco ItauBank S.A'],
            ['id' => 72, 'code' => '376', 'name' => 'Banco J. P. Morgan S.A.'],
            ['id' => 73, 'code' => '074', 'name' => 'Banco J. Safra S.A.'],
            ['id' => 74, 'code' => '217', 'name' => 'Banco John Deere S.A.'],
            ['id' => 75, 'code' => '076', 'name' => 'Banco KDB S.A.'],
            ['id' => 76, 'code' => '757', 'name' => 'Banco KEB HANA do Brasil S.A.'],
            ['id' => 77, 'code' => '600', 'name' => 'Banco Luso Brasileiro S.A.'],
            ['id' => 78, 'code' => '243', 'name' => 'Banco Máxima S.A.'],
            ['id' => 79, 'code' => '720', 'name' => 'Banco Maxinvest S.A.'],
            ['id' => 80, 'code' => '389', 'name' => 'Banco Mercantil de Investimentos S.A.'],
            ['id' => 81, 'code' => '389', 'name' => 'Banco Mercantil do Brasil S.A.'],
            ['id' => 82, 'code' => '370', 'name' => 'Banco Mizuho do Brasil S.A.'],
            ['id' => 83, 'code' => '746', 'name' => 'Banco Modal S.A.'],
            ['id' => 84, 'code' => '066', 'name' => 'Banco Morgan Stanley S.A.'],
            ['id' => 85, 'code' => '456', 'name' => 'Banco MUFG Brasil S.A.'],
            ['id' => 86, 'code' => '007', 'name' => 'Banco Nacional de Desenvolvimento Econômico e Social – BNDES'],
            ['id' => 87, 'code' => '169', 'name' => 'Banco Olé Bonsucesso Consignado S.A.'],
            ['id' => 88, 'code' => '111', 'name' => 'Banco Oliveira Trust Dtvm S.A'],
            ['id' => 89, 'code' => '079', 'name' => 'Banco Original do Agronegócio S.A.'],
            ['id' => 90, 'code' => '212', 'name' => 'Banco Original S.A.'],
            ['id' => 91, 'code' => '712', 'name' => 'Banco Ourinvest S.A.'],
            ['id' => 92, 'code' => '623', 'name' => 'Banco PAN S.A.'],
            ['id' => 93, 'code' => '611', 'name' => 'Banco Paulista S.A.'],
            ['id' => 94, 'code' => '643', 'name' => 'Banco Pine S.A.'],
            ['id' => 95, 'code' => '658', 'name' => 'Banco Porto Real de Investimentos S.A.'],
            ['id' => 96, 'code' => '747', 'name' => 'Banco Rabobank International Brasil S.A.'],
            ['id' => 97, 'code' => '633', 'name' => 'Banco Rendimento S.A.'],
            ['id' => 98, 'code' => '741', 'name' => 'Banco Ribeirão Preto S.A.'],
            ['id' => 99, 'code' => '120', 'name' => 'Banco Rodobens S.A.'],
            ['id' => 100, 'code' => '422', 'name' => 'Banco Safra S.A.'],
            ['id' => 101, 'code' => '033', 'name' => 'Banco Santander (Brasil) S.A.'],
            ['id' => 102, 'code' => '743', 'name' => 'Banco Semear S.A.'],
            ['id' => 103, 'code' => '754', 'name' => 'Banco Sistema S.A.'],
            ['id' => 104, 'code' => '630', 'name' => 'Banco Smartbank S.A.'],
            ['id' => 105, 'code' => '366', 'name' => 'Banco Société Générale Brasil S.A.'],
            ['id' => 106, 'code' => '637', 'name' => 'Banco Sofisa S.A.'],
            ['id' => 107, 'code' => '464', 'name' => 'Banco Sumitomo Mitsui Brasileiro S.A.'],
            ['id' => 108, 'code' => '082', 'name' => 'Banco Topázio S.A.'],
            ['id' => 109, 'code' => '634', 'name' => 'Banco Triângulo S.A.'],
            ['id' => 110, 'code' => '018', 'name' => 'Banco Tricury S.A.'],
            ['id' => 111, 'code' => '655', 'name' => 'Banco Votorantim S.A.'],
            ['id' => 112, 'code' => '610', 'name' => 'Banco VR S.A.'],
            ['id' => 113, 'code' => '119', 'name' => 'Banco Western Union do Brasil S.A.'],
            ['id' => 114, 'code' => '124', 'name' => 'Banco Woori Bank do Brasil S.A.'],
            ['id' => 115, 'code' => '348', 'name' => 'Banco Xp S/A'],
            ['id' => 116, 'code' => '081', 'name' => 'BancoSeguro S.A.'],
            ['id' => 117, 'code' => '021', 'name' => 'BANESTES S.A. Banco do Estado do Espírito Santo'],
            ['id' => 118, 'code' => '755', 'name' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.'],
            ['id' => 119, 'code' => '268', 'name' => 'Barigui Companhia Hipotecária'],
            ['id' => 120, 'code' => '250', 'name' => 'BCV – Banco de Crédito e Varejo S.A.'],
            ['id' => 121, 'code' => '144', 'name' => 'BEXS Banco de Câmbio S.A.'],
            ['id' => 122, 'code' => '253', 'name' => 'Bexs Corretora de Câmbio S/A'],
            ['id' => 123, 'code' => '134', 'name' => 'Bgc Liquidez Dtvm Ltda'],
            ['id' => 124, 'code' => '017', 'name' => 'BNY Mellon Banco S.A.'],
            ['id' => 125, 'code' => '301', 'name' => 'Bpp Instituição De Pagamentos S.A'],
            ['id' => 126, 'code' => '126', 'name' => 'BR Partners Banco de Investimento S.A.'],
            ['id' => 127, 'code' => '070', 'name' => 'BRB – Banco de Brasília S.A.'],
            ['id' => 128, 'code' => '092', 'name' => 'Brickell S.A. Crédito, Financiamento e Investimento'],
            ['id' => 129, 'code' => '173', 'name' => 'BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.'],
            ['id' => 130, 'code' => '142', 'name' => 'Broker Brasil Cc Ltda'],
            ['id' => 131, 'code' => '292', 'name' => 'BS2 Distribuidora de Títulos e Valores Mobiliários S.A.'],
            ['id' => 132, 'code' => '011', 'name' => 'C.Suisse Hedging-Griffo Cv S.A (Credit Suisse)'],
            ['id' => 133, 'code' => '104', 'name' => 'Caixa Econômica Federal'],
            ['id' => 134, 'code' => '288', 'name' => 'Carol Distribuidora de Títulos e Valor Mobiliários Ltda'],
            ['id' => 135, 'code' => '130', 'name' => 'Caruana Scfi'],
            ['id' => 136, 'code' => '159', 'name' => 'Casa Credito S.A'],
            ['id' => 137, 'code' => '016', 'name' => 'Ccm Desp Trâns Sc E Rs'],
            ['id' => 138, 'code' => '089', 'name' => 'Ccr Reg Mogiana'],
            ['id' => 139, 'code' => '114', 'name' => 'Central Cooperativa De Crédito No Estado Do Espírito Santo'],
            ['id' => 140, 'code' => '114-7', 'name' => 'Central das Cooperativas de Economia e Crédito Mútuo doEstado do Espírito Santo Ltda.'],
            ['id' => 141, 'code' => '320', 'name' => 'China Construction Bank (Brasil) Banco Múltiplo S.A.'],
            ['id' => 142, 'code' => '477', 'name' => 'Citibank N.A.'],
            ['id' => 143, 'code' => '180', 'name' => 'Cm Capital Markets Cctvm Ltda'],
            ['id' => 144, 'code' => '127', 'name' => 'Codepe Cvc S.A'],
            ['id' => 145, 'code' => '163', 'name' => 'Commerzbank Brasil S.A. – Banco Múltiplo'],
            ['id' => 146, 'code' => '060', 'name' => 'Confidence Cc S.A'],
            ['id' => 147, 'code' => '085', 'name' => 'Coop Central Ailos'],
            ['id' => 148, 'code' => '097', 'name' => 'Cooperativa Central de Crédito Noroeste Brasileiro Ltda.'],
            ['id' => 149, 'code' => '085-x', 'name' => 'Cooperativa Central de Crédito Urbano-CECRED'],
            ['id' => 150, 'code' => '090-2', 'name' => 'Cooperativa Central de Economia e Crédito Mutuo – SICOOB UNIMAIS'],
            ['id' => 151, 'code' => '087-6', 'name' => 'Cooperativa Central de Economia e Crédito Mútuo das Unicredsde Santa Catarina e Paraná'],
            ['id' => 152, 'code' => '089-2', 'name' => 'Cooperativa de Crédito Rural da Região da Mogiana'],
            ['id' => 153, 'code' => '286', 'name' => 'Cooperativa de Crédito Rural De Ouro'],
            ['id' => 154, 'code' => '279', 'name' => 'Cooperativa de Crédito Rural de Primavera Do Leste'],
            ['id' => 155, 'code' => '273', 'name' => 'Cooperativa de Crédito Rural de São Miguel do Oeste – Sulcredi/São Miguel'],
            ['id' => 156, 'code' => '403', 'name' => 'Banco Cora'],
            ['id' => 157, 'code' => '098', 'name' => 'Credialiança Ccr'],
            ['id' => 158, 'code' => '098-1', 'name' => 'CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL'],
            ['id' => 159, 'code' => '010', 'name' => 'Credicoamo'],
            ['id' => 160, 'code' => '133', 'name' => 'Cresol Confederação'],
            ['id' => 161, 'code' => '182', 'name' => 'Dacasa Financeira S/A'],
            ['id' => 162, 'code' => '707', 'name' => 'Banco Daycoval S.A.'],
            ['id' => 163, 'code' => '487', 'name' => 'Deutsche Bank S.A. – Banco Alemão'],
            ['id' => 164, 'code' => '140', 'name' => 'Easynvest – Título Cv S.A'],
            ['id' => 165, 'code' => '149', 'name' => 'Facta S.A. Cfi'],
            ['id' => 166, 'code' => '285', 'name' => 'Frente Corretora de Câmbio Ltda.'],
            ['id' => 167, 'code' => '278', 'name' => 'Genial Investimentos Corretora de Valores Mobiliários S.A.'],
            ['id' => 168, 'code' => '138', 'name' => 'Get Money Cc Ltda'],
            ['id' => 169, 'code' => '064', 'name' => 'Goldman Sachs do Brasil Banco Múltiplo S.A.'],
            ['id' => 170, 'code' => '177', 'name' => 'Guide Investimentos S.A. Corretora de Valores'],
            ['id' => 171, 'code' => '146', 'name' => 'Guitta Corretora de Câmbio Ltda'],
            ['id' => 172, 'code' => '078', 'name' => 'Haitong Banco de Investimento do Brasil S.A.'],
            ['id' => 173, 'code' => '062', 'name' => 'Hipercard Banco Múltiplo S.A.'],
            ['id' => 174, 'code' => '189', 'name' => 'HS Financeira S/A Crédito, Financiamento e Investimentos'],
            ['id' => 175, 'code' => '269', 'name' => 'HSBC Brasil S.A. – Banco de Investimento'],
            ['id' => 176, 'code' => '271', 'name' => 'IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.'],
            ['id' => 177, 'code' => '157', 'name' => 'Icap Do Brasil Ctvm Ltda'],
            ['id' => 178, 'code' => '132', 'name' => 'ICBC do Brasil Banco Múltiplo S.A.'],
            ['id' => 179, 'code' => '492', 'name' => 'ING Bank N.V.'],
            ['id' => 180, 'code' => '139', 'name' => 'Intesa Sanpaolo Brasil S.A. – Banco Múltiplo'],
            ['id' => 181, 'code' => '652', 'name' => 'Itaú Unibanco Holding S.A.'],
            ['id' => 182, 'code' => '341', 'name' => 'Itaú Unibanco S.A.'],
            ['id' => 183, 'code' => '488', 'name' => 'JPMorgan Chase Bank, National Association'],
            ['id' => 184, 'code' => '399', 'name' => 'Kirton Bank S.A. – Banco Múltiplo'],
            ['id' => 185, 'code' => '293', 'name' => 'Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.'],
            ['id' => 186, 'code' => '105', 'name' => 'Lecca Crédito, Financiamento e Investimento S/A'],
            ['id' => 187, 'code' => '145', 'name' => 'Levycam Ccv Ltda'],
            ['id' => 188, 'code' => '113', 'name' => 'Magliano S.A'],
            ['id' => 189, 'code' => '323', 'name' => 'Mercado Pago – Conta Do Mercado Livre'],
            ['id' => 190, 'code' => '128', 'name' => 'MS Bank S.A. Banco de Câmbio'],
            ['id' => 191, 'code' => '137', 'name' => 'Multimoney Cc Ltda'],
            ['id' => 192, 'code' => '014', 'name' => 'Natixis Brasil S.A. Banco Múltiplo'],
            ['id' => 193, 'code' => '191', 'name' => 'Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.'],
            ['id' => 194, 'code' => '753', 'name' => 'Novo Banco Continental S.A. – Banco Múltiplo'],
            ['id' => 195, 'code' => '260', 'name' => 'Nu Pagamentos S.A (Nubank)'],
            ['id' => 196, 'code' => '613', 'name' => 'Omni Banco S.A.'],
            ['id' => 197, 'code' => '613', 'name' => 'Omni Banco S.A.'],
            ['id' => 198, 'code' => '290', 'name' => 'Pagseguro Internet S.A'],
            ['id' => 199, 'code' => '254', 'name' => 'Paraná Banco S.A.'],
            ['id' => 200, 'code' => '326', 'name' => 'Parati – Crédito Financiamento e Investimento S.A.'],
            ['id' => 201, 'code' => '194', 'name' => 'Parmetal Distribuidora de Títulos e Valores Mobiliários Ltda'],
            ['id' => 202, 'code' => '174', 'name' => 'Pernambucanas Financ S.A'],
            ['id' => 203, 'code' => '100', 'name' => 'Planner Corretora De Valores S.A'],
            ['id' => 204, 'code' => '125', 'name' => 'Plural S.A. – Banco Múltiplo'],
            ['id' => 205, 'code' => '093', 'name' => 'Pólocred Scmepp Ltda'],
            ['id' => 206, 'code' => '108', 'name' => 'Portocred S.A'],
            ['id' => 207, 'code' => '283', 'name' => 'Rb Capital Investimentos Dtvm Ltda'],
            ['id' => 208, 'code' => '101', 'name' => 'Renascenca Dtvm Ltda'],
            ['id' => 209, 'code' => '270', 'name' => 'Sagitur Corretora de Câmbio Ltda.'],
            ['id' => 210, 'code' => '751', 'name' => 'Scotiabank Brasil S.A. Banco Múltiplo'],
            ['id' => 211, 'code' => '276', 'name' => 'Senff S.A. – Crédito, Financiamento e Investimento'],
            ['id' => 212, 'code' => '545', 'name' => 'Senso Ccvm S.A'],
            ['id' => 213, 'code' => '190', 'name' => 'Servicoop'],
            ['id' => 214, 'code' => '183', 'name' => 'Socred S.A'],
            ['id' => 215, 'code' => '299', 'name' => 'Sorocred Crédito, Financiamento e Investimento S.A.'],
            ['id' => 216, 'code' => '118', 'name' => 'Standard Chartered Bank (Brasil) S/A–Bco Invest.'],
            ['id' => 217, 'code' => '197', 'name' => 'Stone Pagamentos S.A'],
            ['id' => 218, 'code' => '340', 'name' => 'Super Pagamentos e Administração de Meios Eletrônicos S.A.'],
            ['id' => 219, 'code' => '095', 'name' => 'Travelex Banco de Câmbio S.A.'],
            ['id' => 220, 'code' => '143', 'name' => 'Treviso Corretora de Câmbio S.A.'],
            ['id' => 221, 'code' => '131', 'name' => 'Tullett Prebon Brasil Cvc Ltda'],
            ['id' => 222, 'code' => '129', 'name' => 'UBS Brasil Banco de Investimento S.A.'],
            ['id' => 223, 'code' => '136', 'name' => 'Unicred Cooperativa'],
            ['id' => 224, 'code' => '099', 'name' => 'UNIPRIME Central – Central Interestadual de Cooperativas de Crédito Ltda.'],
            ['id' => 225, 'code' => '084', 'name' => 'Uniprime Norte do Paraná – Coop de Economia eCrédito Mútuo dos Médicos, Profissionais das Ciências'],
            ['id' => 226, 'code' => '298', 'name' => 'Vips Cc Ltda'],
            ['id' => 227, 'code' => '310', 'name' => 'Vortx Distribuidora de Títulos e Valores Mobiliários Ltda'],
            ['id' => 228, 'code' => '102', 'name' => 'Xp Investimentos S.A'],
        ]);
    }
}
