version: '3'

services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile.laravel
    image: mguizelini/easytoque-backend:prod
    container_name: laravel
    tty: true
    networks:
      - easytoque-network

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    image: mguizelini/nginx:prod
    container_name: nginx
    tty: true
    networks:
      - easytoque-network
    ports:
      - 8080:80

networks:
  easytoque-network:
    driver: bridge
