version: "3"

services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile.laravel
    image: mguizelini/laravel:prod
    container_name: laravel
    volumes:
     - ./storage:/var/www/public/storage
    tty: true
    networks:
      - easytoque-network

  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    tty: true
    networks:
      - easytoque-network

networks:
  easytoque-network:
    driver: bridge
